language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libgoogle-glog-dev
    - libboost-dev
    - libleveldb-dev
    - libboost-system-dev
    - libboost-thread-dev
    - libboost-test-dev
    - librabbitmq-dev
script: make && cd tests && make
